# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "Kepler 6"
subtitle: "Science Fiction Commentary"
email: kepler6mag@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Science Fiction reviews and short stories.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://kepler6.github.io" # the base hostname & protocol for your site
github_username:  kepler6

# Build settings
markdown: kramdown

# oh the collections
collections:
- reviews
- notes
- cats
- paintings
- authors

